### PR TITLE
Transfer and group purging

### PR DESCRIPTION
**Pull request by uhoh-itsmaciek**
Rebased unmerged transfer purging branch; adding group-based purging.

### CODE REVIEW

**Comment by hgmnz** [comment]
+1 looks good

**Comment by hgmnz** [comment]
@tef might wanna give it a look-see

**Comment by tef** [comment]
We're going to want to break this up to purge things in batches, or run this under a separate worker, as not to interrupt or delay scheduling.

**Comment by uhoh-itsmaciek** [comment]
Yeah, that's a good point. I'd forgotten a slow clock job can throw off the whole schedule. I'll take out the loop and just bump up the count a bit as a first step; we can move out to a separate worker if it's not keeping up.

**Comment by uhoh-itsmaciek** [comment]
Pushed a patch to do the above.

**Comment by uhoh-itsmaciek** [comment]
(also added metrics so we can add a Librato dashboard for this)

**Comment by tef** [comment]
I'm ok with this, but i think I will split out the clock to ensure metrics don't get blocked in another PR

**Comment by hgmnz** [comment]
@uhoh-itsmaciek is this mergeable, seems like it? If so, do it up!

**Comment by uhoh-itsmaciek** [comment]
@hgmnz I was running it in staging and noticed some odd log lines I wanted to investigate. I'll do that and get this out today or tomorrow.

**Comment by uhoh-itsmaciek** [comment]
Pending sorting out the deletion issues (which I think is just docs, but want to make sure).

**Comment by tef** [comment]
We haven't heard anything bad after re-enabling deletes, transferatu is stable, I think this is good to merge and deploy now.

**Pull request merged**
