### PR TITLE
Update activesupport and rest-client

### PR DESCRIPTION
**Pull request by cyberdelia**
What could go wrong?

### CODE REVIEW

**Comment by ahamidi** [comment]
Seems like `rest-client` 2.0 is *mostly* backwards compatible, but I'd be happier testing it out in staging before deploying.

**Comment by cyberdelia** [comment]
@ahamidi I'm more afraid of ``activesupport``.

**Comment by ahamidi** [comment]
I assumed that since that's just a Patch version difference, we'd be ok.

**Comment by cyberdelia** [comment]
@ahamidi BE AFRAID, BE VERY AFRAID, MONKEYPATCHING DO NOT CARE ABOUT PATCH VERSIONS.

**Comment by uhoh-itsmaciek** [comment]
@ahamidi let me tell you about the time I spent three days upgrading rails from 4.2.0 to 4.2.7...

**Comment by ahamidi** [comment]
Despite the confidence boosting comments from @uhoh-itsmaciek I think we should probably test this on staging :)

**Comment by cyberdelia** [comment]
@ahamidi Can you give this a run on your staging then?

**Comment by ahamidi** [comment]
@cyberdelia yep, will do

**Comment by ahamidi** [comment]
Tested on staging. Works as expected 👍

**Comment by cyberdelia** [comment]
@ahamidi Want to deploy it to production ?

**Pull request merged**
